### ISSUE TITLE
cssbuilder.CSSBuilder has no field or method CreateVlist

### ISSUE THREAD

**Issue by AlfredoRamos** [boxesandglue/bagme#6]
Hi :wave: 

Thanks for your work on this library.

We've been using this for some time, however since the latest update we can't build our app anymore.

```shell
$ go build -o build/app .
# github.com/speedata/bagme/document
../../../go/pkg/mod/github.com/speedata/bagme@v0.0.0-20231122194752-d1948a8d651e/document/document.go:82:22: d.cssbuilder.CreateVlist undefined (type *cssbuilder.CSSBuilder has no field or method CreateVlist)
```

We detected this with golangci-lint after upgrading the library:

```shell
$ golangci-lint run
[REDACTED].go:25:2: could not import github.com/speedata/bagme/document (-: # github.com/speedata/bagme/document
../../../go/pkg/mod/github.com/speedata/bagme@v0.0.0-20231122194752-d1948a8d651e/document/document.go:82:22: d.cssbuilder.CreateVlist undefined (type *cssbuilder.CSSBuilder has no field or method CreateVlist)) (typecheck)                                                                               
        "github.com/speedata/bagme/document"
        ^
```

And looking in the commit history, it was removed in commit [`53a959b`](https://github.com/speedata/boxesandglue/commit/53a959bc1029df2f691cff67b1facba4f8d1c3a9#diff-3a9ebba367ab01b71114006ccac1fe2a78d7ef50f50b569d0b4e304d0c110cb3).

Our setup:

- Go 1.22.4 linux/amd64
- github.com/speedata/bagme v0.0.0-20231122194752-d1948a8d651e
- github.com/speedata/baseline-pdf v0.0.0-20240621111510-9e70fb550141
- github.com/speedata/boxesandglue v0.0.0-20240621111718-e173db49977c
- github.com/speedata/css/scanner v0.0.0-20201005071706-2ed32c3ce553
- github.com/speedata/gofpdi v1.0.18
- github.com/speedata/hyphenation v1.0.2
- github.com/speedata/textlayout v0.0.0-20230827181055-b7ff752e85ae

**Comment by pgundlach** [comment]
I will push my local changes as soon as possible, probably on Monday, I have changed a lot and it might break things, but I will correct the mistakes...

**Comment by pgundlach** [comment]
Thank you very much for the bug report!

**Comment by pgundlach** [comment]
I have updated some packages, but there are still some loose ends. I will keep working on it the next days hopefully
