### ISSUE TITLE
cssbuilder.go:83:27: undefined: csshtml.PapersizeWidthHeight

### ISSUE THREAD

**Issue by Natsegad** [boxesandglue/bagme#7]
![SS](https://github.com/user-attachments/assets/9d23076b-c481-4de9-86bc-1bbb0588b129)

**Comment by pgundlach** [comment]
Thank you very much for the report, this is very much appreciated! 

Unfortunately I am currently rewriting the HTML backend which is not usable at the moment. See 

https://github.com/boxesandglue

for a status update.

**Comment by OmgProsto** [comment]
@pgundlach 
Please tell me, is there anything I can do now to get around this error?

The library is not working

**Comment by pgundlach** [comment]
I know, and I am sorry. I cannot give you an estimate when this will be fixed, but I am working hard to get everything in sync again. 

Currently I am working from bottom up to the higher level. That is: baseline-pdf, the boxes and glue backend, the frontend and then the HTML/CSS stuff. 

I am also changing the interface (API) of some of the boxes and glue libraries, but I will make them stable as soon as possible. 

This is currently on my todo list on the top place, so while I cannot promise anything, I am uncomfortable with this situation.

**Comment by pgundlach** [comment]
The method is now available, but the library still does not produce sensible output. I keep on working on it, but close this issue.
